[window]
opacity = 0.92
padding.x = 4
padding.y = 4
decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
normal.family = "Iosevka Nerd Font"
#normal.style = "bold"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"
size = 12

[general]
import = ["~/.config/alacritty/cyberdream.toml"]

[selection]
save_to_clipboard = true

[terminal]
[terminal.shell]
program = "/bin/bash"
